- name: Demo on tags
  hosts: localhost
  tasks:
    - name: Fruits
      debug:
        msg: Fruits
      tags:
        - fruits
        - fruit

    - name: Groceries
      debug:
        msg: groceries
      tags:
        - groceries
        - cerals


# Tags can be applied on plays in playbook